services:
    farah:
        image: faulo/farah:8.0
        volumes:
            - ./assets:/var/www/assets
            - ./scripts:/var/www/scripts
            - ./src:/var/www/src
            - ./html:/var/www/html
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        networks:
            - vhosts_default
networks:
    vhosts_default:
        external: true